"""
데이터 내보내기 & 리포트 생성 모듈
- 엑셀/CSV 내보내기
- PDF 리포트 생성
- 차트 이미지 저장
"""
import pandas as pd
import os
from datetime import datetime
from typing import Dict
import io
import plotly.graph_objects as go

class DataExporter:
    """데이터 내보내기"""
    
    def __init__(self, export_dir: str = "exports"):
        self.export_dir = export_dir
        os.makedirs(export_dir, exist_ok=True)
    
    def export_to_excel(self, data: Dict[str, pd.DataFrame], 
                       filename: str = None) -> str:
        """여러 데이터프레임을 하나의 엑셀 파일로 저장
        
        Args:
            data: {sheet_name: dataframe}
            filename: 파일명 (없으면 자동 생성)
        
        Returns:
            저장된 파일 경로
        """
        if filename is None:
            filename = f"stockvibe_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        
        filepath = os.path.join(self.export_dir, filename)
        
        with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
            for sheet_name, df in data.items():
                df.to_excel(writer, sheet_name=sheet_name, index=False)
        
        return filepath
    
    def export_to_csv(self, df: pd.DataFrame, filename: str = None) -> str:
        """CSV 파일로 저장"""
        if filename is None:
            filename = f"stockvibe_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        
        filepath = os.path.join(self.export_dir, filename)
        df.to_csv(filepath, index=False, encoding='utf-8-sig')
        
        return filepath
    
    def create_download_link(self, df: pd.DataFrame, 
                           format: str = 'csv') -> bytes:
        """Streamlit 다운로드용 버퍼 생성"""
        if format == 'csv':
            return df.to_csv(index=False, encoding='utf-8-sig').encode('utf-8-sig')
        elif format == 'excel':
            buffer = io.BytesIO()
            with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                df.to_excel(writer, index=False)
            return buffer.getvalue()
        else:
            raise ValueError(f"Unsupported format: {format}")


class ReportGenerator:
    """리포트 생성"""
    
    @staticmethod
    def generate_stock_report(code: str, name: str, analysis_data: Dict) -> str:
        """종목 분석 리포트 (Markdown)
        
        Args:
            code: 종목코드
            name: 종목명
            analysis_data: 분석 결과 딕셔너리
        
        Returns:
            Markdown 형식 리포트
        """
        report = f"""# 📊 {name} ({code}) 분석 리포트

**생성일시**: {datetime.now().strftime('%Y년 %m월 %d일 %H:%M')}

---

## 1. 현재 주가 정보

- **현재가**: {analysis_data.get('current_price', 'N/A'):,}원
- **등락률**: {analysis_data.get('change_rate', 0):.2f}%
- **거래량**: {analysis_data.get('volume', 'N/A'):,}
- **시가총액**: {analysis_data.get('market_cap', 'N/A')}

---

## 2. AI 예측 분석

### 종합 점수
- **AI 점수**: {analysis_data.get('ai_score', 0):.1f}/100
- **투자 의견**: {analysis_data.get('recommendation', 'N/A')}

### 분석 근거
{analysis_data.get('reasoning', '분석 데이터가 없습니다.')}

---

## 3. 기술적 지표

- **RSI(14)**: {analysis_data.get('rsi', 'N/A')}
- **MACD**: {analysis_data.get('macd', 'N/A')}
- **이동평균**:
  - MA5: {analysis_data.get('ma5', 'N/A')}원
  - MA20: {analysis_data.get('ma20', 'N/A')}원
  - MA60: {analysis_data.get('ma60', 'N/A')}원

---

## 4. 재무 정보

- **PER**: {analysis_data.get('per', 'N/A')}
- **PBR**: {analysis_data.get('pbr', 'N/A')}
- **ROE**: {analysis_data.get('roe', 'N/A')}%
- **영업이익률**: {analysis_data.get('operating_margin', 'N/A')}%

---

## 5. 최근 뉴스

{analysis_data.get('recent_news', '뉴스 데이터가 없습니다.')}

---

## 6. 투자 유의사항

⚠️ 본 리포트는 AI 기반 분석 결과이며, 투자 판단의 참고 자료로만 활용해야 합니다.
실제 투자 시에는 추가적인 조사와 전문가 상담이 필요합니다.

---

*Generated by StockVibe - AI Stock Analysis System*
"""
        return report
    
    @staticmethod
    def generate_portfolio_report(portfolio_data: pd.DataFrame, 
                                  summary: Dict) -> str:
        """포트폴리오 리포트 생성"""
        
        # 포트폴리오 테이블
        portfolio_table = portfolio_data.to_markdown(index=False) if not portfolio_data.empty else "보유 종목이 없습니다."
        
        report = f"""# 💼 포트폴리오 분석 리포트

**생성일시**: {datetime.now().strftime('%Y년 %m월 %d일 %H:%M')}

---

## 📈 종합 현황

- **총 평가금액**: {summary.get('total_value', 0):,.0f}원
- **총 매입금액**: {summary.get('total_purchase', 0):,.0f}원
- **총 평가손익**: {summary.get('total_profit', 0):,.0f}원
- **수익률**: {summary.get('total_profit_rate', 0):.2f}%
- **보유 종목 수**: {summary.get('num_stocks', 0)}개

---

## 📊 보유 종목 상세

{portfolio_table}

---

## 💡 투자 제안

"""
        
        # 수익률 기준 제안
        if summary.get('total_profit_rate', 0) > 10:
            report += "✅ 우수한 수익률을 기록하고 있습니다. 일부 수익 실현을 고려해보세요.\n"
        elif summary.get('total_profit_rate', 0) < -10:
            report += "⚠️ 손실이 발생하고 있습니다. 포트폴리오 재조정을 검토해보세요.\n"
        else:
            report += "📊 안정적인 수익률을 유지하고 있습니다.\n"
        
        report += """
---

*Generated by StockVibe - Portfolio Management System*
"""
        return report
    
    @staticmethod
    def generate_comparison_report(comparison_df: pd.DataFrame) -> str:
        """종목 비교 리포트"""
        
        comparison_table = comparison_df.to_markdown(index=False) if not comparison_df.empty else "비교 데이터가 없습니다."
        
        report = f"""# 🔍 종목 비교 분석 리포트

**생성일시**: {datetime.now().strftime('%Y년 %m월 %d일 %H:%M')}
**비교 종목 수**: {len(comparison_df)}개

---

## 📊 종목 비교표

{comparison_table}

---

## 💡 분석 결과

"""
        
        if not comparison_df.empty:
            # 최고 AI 점수
            top_stock = comparison_df.iloc[0]
            report += f"**AI 점수 1위**: {top_stock['종목명']} ({top_stock['AI점수']:.1f}점)\n\n"
            
            # 최고 등락률
            best_performer = comparison_df.nlargest(1, '등락률').iloc[0]
            report += f"**등락률 1위**: {best_performer['종목명']} ({best_performer['등락률']:.2f}%)\n\n"
        
        report += """
---

*Generated by StockVibe - Comparison Analysis System*
"""
        return report


class ChartExporter:
    """차트 내보내기"""
    
    def __init__(self, export_dir: str = "exports/charts"):
        self.export_dir = export_dir
        os.makedirs(export_dir, exist_ok=True)
    
    def export_plotly_chart(self, fig: go.Figure, filename: str = None, 
                           format: str = 'png') -> str:
        """Plotly 차트를 이미지로 저장
        
        Args:
            fig: Plotly Figure 객체
            filename: 파일명
            format: 'png', 'jpeg', 'svg', 'pdf'
        """
        if filename is None:
            filename = f"chart_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{format}"
        
        filepath = os.path.join(self.export_dir, filename)
        
        try:
            # kaleido 패키지 필요
            fig.write_image(filepath, format=format, width=1200, height=600)
            return filepath
        except Exception as e:
            # kaleido 없을 경우 HTML로 저장
            html_path = filepath.replace(f'.{format}', '.html')
            fig.write_html(html_path)
            return html_path
    
    def export_chart_as_html(self, fig: go.Figure, filename: str = None) -> str:
        """차트를 인터랙티브 HTML로 저장"""
        if filename is None:
            filename = f"chart_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        
        filepath = os.path.join(self.export_dir, filename)
        fig.write_html(filepath)
        
        return filepath
