from __future__ import annotations

import pandas as pd
import streamlit as st

from app.data import load_kospi_index, load_kospi_list, load_marketcap_history, load_stock_data
from app.data_pipeline import build_stock_master_df
from app.investment_engine import InvestmentEngine
from app.market_regime import run_market_regime_engine
from app.market_structure_ui import _load_sector_rank_history_cached
from app.marketcap_bump import build_marketcap_rank_history
from app.money_flow_engine import MoneyFlowEngine
from app.outcome_tracker import log_decision
from app.sector_prediction_engine import SectorPredictionEngine
from app.settings import UserSettings


@st.cache_data(ttl=3600, show_spinner=False)
def _load_stock_master_cached(data_dir: str = "data") -> pd.DataFrame:
    return build_stock_master_df(data_dir)


@st.cache_data(ttl=3600, show_spinner=False)
def _load_marketcap_rank_cached(data_dir: str = "data") -> pd.DataFrame:
    stock_master_df = build_stock_master_df(data_dir)
    sector_map = stock_master_df[["code", "sector"]].copy() if not stock_master_df.empty else pd.DataFrame(columns=["code", "sector"])
    marketcap_df = load_marketcap_history(data_dir)
    return build_marketcap_rank_history(
        marketcap_df=marketcap_df,
        sector_map_df=sector_map,
        freq="W",
        top_n=10,
    )


def _render_why_this_stock(row: pd.Series) -> None:
    stock = str(row.get("stock", "-"))
    sector = str(row.get("sector", "-"))
    sector_power = float(pd.to_numeric(row.get("sector_power", 0.0), errors="coerce"))
    financial_score = float(pd.to_numeric(row.get("financial_score", 0.0), errors="coerce"))
    momentum_score = float(pd.to_numeric(row.get("momentum_score", 0.0), errors="coerce"))
    signal = str(row.get("signal", "")).upper()
    strategy = str(row.get("triggered_strategy", "-")).strip() or "-"
    regime = str(row.get("market_regime", "UNKNOWN"))

    reasons = []
    if sector_power >= 60:
        reasons.append("This stock belongs to a leading sector.")
    if financial_score >= 60 and momentum_score >= 50:
        reasons.append("Momentum and financial strength are strong.")
    elif financial_score >= 60:
        reasons.append("Financial strength is solid.")
    elif momentum_score >= 50:
        reasons.append("Momentum is supportive.")

    if signal == "BUY":
        reasons.append("Signal generated by validated strategy.")
    sector_pred = float(pd.to_numeric(row.get("sector_prediction_score", 50.0), errors="coerce"))
    if sector_pred >= 70:
        reasons.append("Sector prediction indicates incoming capital rotation.")
    if not reasons:
        reasons.append("Composite score remains competitive versus peers.")

    st.markdown(f"**Why this stock? · {stock}**")
    st.caption(f"Sector: {sector} | Regime: {regime} | Triggered strategy: {strategy}")
    for reason in reasons:
        st.write(f"- {reason}")


def render_investment_candidates_page() -> None:
    data_dir = "data"
    st.title("📈 투자 후보")
    st.caption("시장/섹터/전략/재무/모멘텀 신호를 통합한 최종 투자 후보 랭킹입니다.")
    settings = UserSettings(data_dir).load_settings()
    use_adaptive_weights = bool(settings.get("use_adaptive_weights", False))

    stock_master_df = _load_stock_master_cached(data_dir)
    stock_df = load_stock_data(data_dir)
    name_df = load_kospi_list(data_dir)
    sector_rank_df = _load_sector_rank_history_cached(data_dir)
    kospi_index_df = load_kospi_index(data_dir)
    marketcap_rank_df = _load_marketcap_rank_cached(data_dir)

    if stock_master_df is None or stock_master_df.empty:
        st.warning("투자 후보를 계산할 데이터가 없습니다.")
        return

    regime_result = run_market_regime_engine(
        stock_master_df=stock_master_df,
        kospi_index_df=kospi_index_df,
        sector_rank_df=sector_rank_df,
        marketcap_rank_df=marketcap_rank_df,
    )
    current_regime = regime_result.get("primary_regime", "UNKNOWN") if isinstance(regime_result, dict) else "UNKNOWN"

    # Money flow score integration
    if stock_df is not None and not stock_df.empty:
        flow_input = stock_df.copy()
        flow_input["code"] = flow_input["code"].astype(str).str.zfill(6)
        sector_map = stock_master_df[["code", "sector"]].copy() if "code" in stock_master_df.columns else pd.DataFrame(columns=["code", "sector"])
        if not sector_map.empty:
            sector_map["code"] = sector_map["code"].astype(str).str.zfill(6)
            sector_map = sector_map.drop_duplicates(subset=["code"], keep="last")
            flow_input = flow_input.merge(sector_map, on="code", how="left")
        if name_df is not None and not name_df.empty:
            nm = name_df[["code", "name"]].copy()
            nm["code"] = nm["code"].astype(str).str.zfill(6)
            flow_input = flow_input.merge(nm, on="code", how="left")

        money_engine = MoneyFlowEngine()
        stock_flow_df = money_engine.compute_stock_money_flow(flow_input)
        stock_flow_df = money_engine.compute_flow_score(stock_flow_df)

        if stock_flow_df is not None and not stock_flow_df.empty and "code" in stock_master_df.columns:
            flow_merge = stock_flow_df[["code", "flow_score"]].copy()
            flow_merge["code"] = flow_merge["code"].astype(str).str.zfill(6)
            stock_master_df = stock_master_df.copy()
            stock_master_df["code"] = stock_master_df["code"].astype(str).str.zfill(6)
            stock_master_df = stock_master_df.merge(flow_merge, on="code", how="left")
            stock_master_df["money_flow_score"] = pd.to_numeric(stock_master_df.get("flow_score"), errors="coerce").fillna(50.0)

        # Sector prediction score integration
        if stock_flow_df is not None and not stock_flow_df.empty:
            pred_engine = SectorPredictionEngine()
            sector_flow_df = money_engine.compute_sector_money_flow(stock_flow_df)
            sector_flow_df = money_engine.compute_flow_score(sector_flow_df)

            sm_pred = stock_master_df.copy()
            sm_pred["money_flow_score"] = pd.to_numeric(sm_pred.get("money_flow_score", 50.0), errors="coerce").fillna(50.0)
            features_df = pred_engine.compute_sector_features(sector_flow_df, sector_rank_df, sm_pred)
            pred_df = pred_engine.compute_prediction_score(features_df)
            pred_df = pred_engine.classify_sector_state(pred_df)

            if pred_df is not None and not pred_df.empty and "sector" in stock_master_df.columns:
                sector_pred = pred_df[["sector", "prediction_score"]].copy().drop_duplicates(subset=["sector"], keep="last")
                stock_master_df = stock_master_df.merge(sector_pred, on="sector", how="left")
                stock_master_df["sector_prediction_score"] = pd.to_numeric(stock_master_df.get("prediction_score"), errors="coerce").fillna(50.0)

    engine = InvestmentEngine()
    investment_df = engine.build_investment_df(
        stock_master_df=stock_master_df,
        sector_rank_df=sector_rank_df,
        regime=current_regime,
    )
    scored_df = engine.compute_investment_score(
        investment_df,
        use_adaptive_weights=use_adaptive_weights,
        data_dir=data_dir,
    )
    buy_df = engine.filter_buy_candidates(scored_df)
    ranked_df = engine.rank_candidates(buy_df)

    st.markdown("### Top Investment Candidates")
    if ranked_df.empty:
        st.info("현재 규칙을 만족하는 투자 후보가 없습니다.")
        return

    decision_date = str(regime_result.get("as_of_date", pd.Timestamp.now().strftime("%Y-%m-%d")))
    for _, row in ranked_df.iterrows():
        log_decision(
            {
                "source": "investment_candidates",
                "decision_date": decision_date,
                "code": row.get("code", ""),
                "stock": row.get("stock", ""),
                "sector": row.get("sector", ""),
                "signal": row.get("signal", "BUY"),
                "triggered_strategy": row.get("triggered_strategy", ""),
                "market_regime": current_regime,
                "investment_score": row.get("investment_score", None),
                "sector_power": row.get("sector_power", None),
                "financial_score": row.get("financial_score", None),
                "momentum_score": row.get("momentum_score", None),
                "signal_strength": row.get("signal_strength", None),
                "strategy_fit": row.get("strategy_fit", None),
                "money_flow_score": row.get("money_flow_score", None),
                "sector_prediction_score": row.get("sector_prediction_score", None),
                "confidence": regime_result.get("confidence", None),
            }
        )

    display_cols = ["rank", "stock", "sector", "investment_score", "sector_prediction_score", "signal", "triggered_strategy"]
    st.dataframe(
        ranked_df[display_cols],
        hide_index=True,
        use_container_width=True,
        column_config={
            "rank": st.column_config.NumberColumn("rank", format="%d"),
            "stock": st.column_config.TextColumn("stock"),
            "sector": st.column_config.TextColumn("sector"),
            "investment_score": st.column_config.NumberColumn("investment_score", format="%.2f"),
            "sector_prediction_score": st.column_config.NumberColumn("sector_prediction_score", format="%.2f"),
            "signal": st.column_config.TextColumn("signal"),
            "triggered_strategy": st.column_config.TextColumn("triggered_strategy"),
        },
    )
    st.caption(f"적응형 가중치 사용: {'ON' if use_adaptive_weights else 'OFF'}")

    st.divider()
    st.markdown("### 📝 Insight Card")

    top_n = min(3, len(ranked_df))
    for idx in range(top_n):
        row = ranked_df.iloc[idx]
        with st.container(border=True):
            _render_why_this_stock(row)
